### ISSUE TITLE
actual_angle and target_angle maximum is always 360

### ISSUE THREAD

**Issue by muhlba91** [hella-info/onyx_api#2]
Checking on device data, the maximum value for `actual_angle` and `target_angle` is always `360`.

From testing, the shutters/raffstores support  only the following maximum value depending on their type:
- rollershutter: 0 (setting an angle is simply ignored)
- raffstore_90: 90
- raffstore_180: 180

This limits the ability to rely on the reported properties and I have to calculate the maximum angle manually in relation to the set type.

**Comment by profer** [comment]
This is intentional because we perform bounds checks on property values before sending them to the individual devices. 

Having 0-360 as the angle range for `rollershutter`, `raffstore_90`, `raffstore_180`, etc. allows us to send the same command to a mixed group of devices and not worry about triggering the bounds check.

We might change the ranges to the physical limits of the devices in the future and remove the additional bounds check but there are no immediate plans for it. You'll have to rely on the device type for now.

**Comment by muhlba91** [comment]
Thank you for that information - it makes it clear now and how those values have to be handled. 👍
