### ISSUE TITLE
sun_brightness_class was removed

### ISSUE THREAD

**Issue by hfrmobile** [hella-info/onyx_api#5]
The `sun_brightness_class` property was removed for ONYX.WEATHER in API v1 which will break customers code when using that property!

Such changes shouldn't be made for released APIs. That can be done in v2, but not in v1 so that the customers/developers having the choice to use (older API or update to newer API ...).

Also missing "What's new" and documentation for v1.

**Comment by profer** [comment]
Thank you for bringing this problem to our attention.

Property access through the API is currently implemented via runtime introspection which allows access to all properties that are published by a device in the ONYX network and includes legacy properties that we intend to remove in the future. This is the reason why we have the following caveat in the [Device Properties and Actions](https://github.com/hella-info/onyx_api#device-properties-and-actions-1) section of the API documentation:

> This section describes the most important properties and actions for the supported device types. **API access to properties not in this document may be restricted in the future and should be avoided.**

The `sun_brightness_class` property was one such property and was removed from the weather station firmware because there were problems with its implementation, it was not used by ONYX internally and not listed in the API documentation.

To make sure we won't break API clients in the future we plan to implement a property whitelist in one of the upcoming releases that restricts property access to only the officially supported ones.
