### ISSUE TITLE
API v3: switch_drive_direction property removed

### ISSUE THREAD

**Issue by muhlba91** [hella-info/onyx_api#6]
In the newly released API v3, `animation` got introduced instead of drivetime and rotationtime up/down.

However, the property `switch_drive_direction` seems to be still supported in the (iOS) application and was an indicator if the values of open/close (0, 100) are inverted.
For example, the Home Assistant integration relied on this property to invert the positions accordingly.

Will this property (or a successor) be exposed again, or is this being handled entirely differently now with API v3?

As a reference I can provide https://github.com/muhlba91/onyx-homeassistant-integration/issues/8#issuecomment-975634478.
- Shutters/Raffstores I use seem to have "inverted" values in comparison to how Home Assistant is expecting them.
- Awnings (Markise) seems to have an inverted value (compared to v2 incl. inversion computation using `switch_drive_direction`.

**Comment by profer** [comment]
We removed the `switch_drive_direction` property for exactly that reason and because it is safety critical that this property is set correctly via the ONYX app. I'll try to explain:

For all currently supported shading products (awnings, roller shutters, raffstores, ...), position `0` means fully retracted and position `100` means fully extended. Because the shading motors are not always mounted on the same side in the products we need the `switch_drive_direction` property internally to know if the motor should be rotated clockwise or counterclockwise to get to position 0.

Unfortunately the naming of the `open` and `close` actions often causes some confusion, because most users intuitively reverse their meaning when talking about awnings. To handle all products the same way we defined `open` to always move to position 0, that means retract the device, and `close` to always move to position `100` and extend the device as stated in the [API documentation](https://github.com/hella-info/onyx_api#motor-controllers).

Our safety automations and integrations with external systems also rely on this behavior. The wind protection for example, would extend awnings instead of retract them if `switch_drive_direction` is configured incorrectly which could be very dangerous.

I strongly suspect that in https://github.com/muhlba91/onyx-homeassistant-integration/issues/8#issuecomment-975634478 the affected devices are configured incorrectly and also move in the wrong direction when controlled via the ONYX app, i.e. the visualization in the app moves in the opposite direction from the real device. If that is indeed the case, the drive direction _must_ be swapped via the ONYX app to ensure safe operation.

**Comment by muhlba91** [comment]
Thanks for this explanation - now the removal makes way more sense!

Just to be sure: this means for all devices `0` means the device is open (e.g. the raffstore is retracted and does not cover the window) and `100` is always the opposite (e.g. raffstore is fully covering the window)?
No matter how the `switch_drive_direction` is set, if I instruct the raffstore to set its position to `0` it will always fully retract?

To be honest, this is now more intuitive now. :+1:

**Comment by profer** [comment]
Exactly right. If any device moves in the opposite direction, i.e. closes when moving to position `0`, this is a configuration error and must be corrected using our app.

**Comment by muhlba91** [comment]
Thanks for confirmation - now everything is clear. Will close the issue. 😃
